-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 21:42:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemaOficina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemaOficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaOficina` DEFAULT CHARACTER SET utf8 ;
USE `sistemaOficina` ;

-- -----------------------------------------------------
-- Table `sistemaOficina`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaOficina`.`mecanico` (
  `idMecanicos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMecanicos`),
  UNIQUE INDEX `idMecanicos_UNIQUE` (`idMecanicos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaOficina`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaOficina`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaOficina`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaOficina`.`servico` (
  `idServicos` INT NOT NULL AUTO_INCREMENT,
  `tipoDeServico` VARCHAR(100) NOT NULL,
  `valor` FLOAT NOT NULL,
  `homemHora` INT NOT NULL,
  PRIMARY KEY (`idServicos`),
  UNIQUE INDEX `idServicos_UNIQUE` (`idServicos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaOficina`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaOficina`.`peca` (
  `idPeca` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idPeca`),
  UNIQUE INDEX `idPeca_UNIQUE` (`idPeca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaOficina`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaOficina`.`veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(9) NOT NULL,
  `chassis` VARCHAR(17) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `cliente_idCliente`),
  INDEX `fk_veiculo_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE,
  UNIQUE INDEX `idVeiculo_UNIQUE` (`idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `sistemaOficina`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaOficina`.`ordemDeServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaOficina`.`ordemDeServico` (
  `idOrdemDeServico` INT NOT NULL AUTO_INCREMENT,
  `dataEmissao` DATETIME NOT NULL,
  `valor` FLOAT NOT NULL,
  `statusServico` ENUM('Aberto', 'EmExecução', 'aguardandoPeça', 'Concluida') NOT NULL,
  `dataConclusao` DATETIME NOT NULL,
  `statusAprovacao` ENUM('Sim', 'Nao', 'Aguardando') NOT NULL,
  `mecanico_idMecanicos` INT NOT NULL,
  `veiculo_idVeiculo` INT NOT NULL,
  `veiculo_cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdemDeServico`, `mecanico_idMecanicos`, `veiculo_idVeiculo`, `veiculo_cliente_idCliente`),
  INDEX `fk_ordemDeServico_mecanico1_idx` (`mecanico_idMecanicos` ASC) VISIBLE,
  INDEX `fk_ordemDeServico_veiculo1_idx` (`veiculo_idVeiculo` ASC, `veiculo_cliente_idCliente` ASC) VISIBLE,
  UNIQUE INDEX `idOrdemDeServico_UNIQUE` (`idOrdemDeServico` ASC) VISIBLE,
  CONSTRAINT `fk_ordemDeServico_mecanico1`
    FOREIGN KEY (`mecanico_idMecanicos`)
    REFERENCES `sistemaOficina`.`mecanico` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemDeServico_veiculo1`
    FOREIGN KEY (`veiculo_idVeiculo` , `veiculo_cliente_idCliente`)
    REFERENCES `sistemaOficina`.`veiculo` (`idVeiculo` , `cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaOficina`.`servicoAplicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaOficina`.`servicoAplicado` (
  `ordemDeServico_idOrdemDeServico` INT NOT NULL,
  `servico_idServicos` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`ordemDeServico_idOrdemDeServico`, `servico_idServicos`),
  INDEX `fk_ordemDeServico_has_servico_servico1_idx` (`servico_idServicos` ASC) VISIBLE,
  INDEX `fk_ordemDeServico_has_servico_ordemDeServico1_idx` (`ordemDeServico_idOrdemDeServico` ASC) VISIBLE,
  CONSTRAINT `fk_ordemDeServico_has_servico_ordemDeServico1`
    FOREIGN KEY (`ordemDeServico_idOrdemDeServico`)
    REFERENCES `sistemaOficina`.`ordemDeServico` (`idOrdemDeServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemDeServico_has_servico_servico1`
    FOREIGN KEY (`servico_idServicos`)
    REFERENCES `sistemaOficina`.`servico` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaOficina`.`pecaUtilizada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaOficina`.`pecaUtilizada` (
  `ordemDeServico_idOrdemDeServico` INT NOT NULL,
  `peca_idPeca` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`ordemDeServico_idOrdemDeServico`, `peca_idPeca`),
  INDEX `fk_ordemDeServico_has_peca_peca1_idx` (`peca_idPeca` ASC) VISIBLE,
  INDEX `fk_ordemDeServico_has_peca_ordemDeServico1_idx` (`ordemDeServico_idOrdemDeServico` ASC) VISIBLE,
  CONSTRAINT `fk_ordemDeServico_has_peca_ordemDeServico1`
    FOREIGN KEY (`ordemDeServico_idOrdemDeServico`)
    REFERENCES `sistemaOficina`.`ordemDeServico` (`idOrdemDeServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemDeServico_has_peca_peca1`
    FOREIGN KEY (`peca_idPeca`)
    REFERENCES `sistemaOficina`.`peca` (`idPeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
