insert into peca (quantidade, descricao, valor) values ('5', 'Metoprolol Tartrate and Hydrochlorothiazide', 30.04);
insert into peca (quantidade, descricao, valor) values ('1', 'Tolnaftate', 5.1);
insert into peca (quantidade, descricao, valor) values ('7', 'Naproxen Sodium', 42.49);
insert into peca (quantidade, descricao, valor) values ('0', 'hybrid CF', 32.51);
insert into peca (quantidade, descricao, valor) values ('0', 'Telmisartan and Amlodipine', 18.15);
insert into peca (quantidade, descricao, valor) values ('5', 'Badger Unscented SPF 15 Sunscreen', 66.33);
insert into peca (quantidade, descricao, valor) values ('2', 'Treatment Set TS340796', 74.89);
insert into peca (quantidade, descricao, valor) values ('4', 'Primaquine Phosphate', 99.57);
insert into peca (quantidade, descricao, valor) values ('0', 'Wheat Smut', 3.3);
insert into peca (quantidade, descricao, valor) values ('7', 'Up and Up Cold Flu Relief', 6.83);
insert into peca (quantidade, descricao, valor) values ('3', 'Ponds', 70.07);
insert into peca (quantidade, descricao, valor) values ('9', 'Rohto Arctic', 32.9);
insert into peca (quantidade, descricao, valor) values ('4', 'Lidocaine Hydrochloride', 45.36);
insert into peca (quantidade, descricao, valor) values ('6', 'Leader', 7.59);
insert into peca (quantidade, descricao, valor) values ('7', 'NALOXONE HYDROCHLORIDE', 42.08);
insert into peca (quantidade, descricao, valor) values ('5', 'Apis Belladonna Mercurius', 95.09);
insert into peca (quantidade, descricao, valor) values ('5', 'acetic acid', 16.86);
insert into peca (quantidade, descricao, valor) values ('0', 'Erythromycin', 28.25);
insert into peca (quantidade, descricao, valor) values ('4', 'Babor Body Line Thermal Smooth Effect Body', 31.04);
insert into peca (quantidade, descricao, valor) values ('3', 'Upset Stomach Relief to Go', 2.06);
insert into peca (quantidade, descricao, valor) values ('3', 'Hemostatic Solution', 79.32);
insert into peca (quantidade, descricao, valor) values ('5', 'Vespa crabro ex animale 6 Special Order', 5.05);
insert into peca (quantidade, descricao, valor) values ('7', 'Bayer', 54.13);
insert into peca (quantidade, descricao, valor) values ('0', 'Eye Wash', 87.25);
insert into peca (quantidade, descricao, valor) values ('3', 'Loratadine', 77.01);
insert into peca (quantidade, descricao, valor) values ('0', 'Synthroid', 30.35);
insert into peca (quantidade, descricao, valor) values ('9', 'Cover Fx Blemish Treatment Concealer N Deep', 25.2);
insert into peca (quantidade, descricao, valor) values ('5', 'Western Juniper', 21.72);
insert into peca (quantidade, descricao, valor) values ('2', 'Crayola', 54.61);
insert into peca (quantidade, descricao, valor) values ('2', 'Disney Fairies Antibacterial Hand Wipes', 20.13);
insert into peca (quantidade, descricao, valor) values ('4', 'Clindamycin hydrochloride', 28.28);
insert into peca (quantidade, descricao, valor) values ('9', 'Simvastatin', 30.24);
insert into peca (quantidade, descricao, valor) values ('3', 'Bupropion Hydrochloride', 15.36);
insert into peca (quantidade, descricao, valor) values ('5', 'Loperamide Hydrochloride', 8.5);
insert into peca (quantidade, descricao, valor) values ('7', 'XtraCare Creamy Petroleum Jelly', 66.46);
insert into peca (quantidade, descricao, valor) values ('8', 'Ipratropium Bromide', 84.11);
insert into peca (quantidade, descricao, valor) values ('2', 'Zep Anti-Bacterial Foaming Hand Cleaner', 65.51);
insert into peca (quantidade, descricao, valor) values ('3', 'LIFT LUMIERE', 16.19);
insert into peca (quantidade, descricao, valor) values ('4', 'Flurbiprofen', 73.82);
insert into peca (quantidade, descricao, valor) values ('2', 'CINA', 45.43);
insert into peca (quantidade, descricao, valor) values ('4', 'LANOXIN', 59.09);
insert into peca (quantidade, descricao, valor) values ('1', 'Cefuroxime Axetil', 75.21);
insert into peca (quantidade, descricao, valor) values ('4', 'Carbon Dioxide Oxygen Mixture', 17.58);
insert into peca (quantidade, descricao, valor) values ('5', 'Russian Thistle', 60.03);
insert into peca (quantidade, descricao, valor) values ('1', 'Tacrolimus', 17.69);
insert into peca (quantidade, descricao, valor) values ('5', 'Head and Shoulders 2in1', 91.89);
insert into peca (quantidade, descricao, valor) values ('2', 'Hydrochlorothiazide', 57.44);
insert into peca (quantidade, descricao, valor) values ('1', 'Lisinopril', 64.36);
insert into peca (quantidade, descricao, valor) values ('9', 'Nortriptyline Hydrochloride', 62.87);
insert into peca (quantidade, descricao, valor) values ('1', 'WELLBUTRIN', 91.55);
insert into peca (quantidade, descricao, valor) values ('1', 'M EROS LIQUID', 19.51);
insert into peca (quantidade, descricao, valor) values ('8', 'Gabapentin', 8.41);
insert into peca (quantidade, descricao, valor) values ('2', 'Listerine Smart Rinse', 94.88);
insert into peca (quantidade, descricao, valor) values ('2', 'Pamprin Multisymptom Menstrual Pain Relief', 8.58);
insert into peca (quantidade, descricao, valor) values ('7', 'Cold Sore Treatment', 53.28);
insert into peca (quantidade, descricao, valor) values ('3', 'ATORVASTATIN CALCIUM', 7.92);
insert into peca (quantidade, descricao, valor) values ('0', 'Levofloxacin', 59.52);
insert into peca (quantidade, descricao, valor) values ('6', 'No7 Protect and Perfect Intense Day Cream Sunscreen Broad Spectrum SPF 15', 16.23);
insert into peca (quantidade, descricao, valor) values ('9', 'Cepacol', 86.79);
insert into peca (quantidade, descricao, valor) values ('9', 'Azithromycin', 37.66);
insert into peca (quantidade, descricao, valor) values ('8', 'Lovastatin', 4.08);
insert into peca (quantidade, descricao, valor) values ('0', 'Isoniazid', 74.7);
insert into peca (quantidade, descricao, valor) values ('4', 'benzonatate', 70.4);
insert into peca (quantidade, descricao, valor) values ('8', 'good neighbor pharmacy cold', 45.78);
insert into peca (quantidade, descricao, valor) values ('5', 'Risperidone', 76.07);
insert into peca (quantidade, descricao, valor) values ('3', 'SHISEIDO BENEFIANCE WRINKLERESIST24 DAY', 36.09);
insert into peca (quantidade, descricao, valor) values ('7', 'ALLEROFF', 43.93);
insert into peca (quantidade, descricao, valor) values ('7', 'Pleo Reb', 44.04);
insert into peca (quantidade, descricao, valor) values ('4', 'Valsartan and Hydrochlorothiazide', 78.0);
insert into peca (quantidade, descricao, valor) values ('0', 'Foods', 72.47);
insert into peca (quantidade, descricao, valor) values ('5', 'Cepacol Sore Throat Maximum Numbing Honey Lemon', 67.86);
insert into peca (quantidade, descricao, valor) values ('2', 'Vanilla Cupcake Anti Bacterial Hand Sanitizer', 93.42);
insert into peca (quantidade, descricao, valor) values ('6', 'Mononine', 32.14);
insert into peca (quantidade, descricao, valor) values ('8', 'MILK OF MAGNESIA ORIGINAL', 1.15);
insert into peca (quantidade, descricao, valor) values ('0', 'MINOXIDIL', 21.3);
insert into peca (quantidade, descricao, valor) values ('2', 'Visine Tears', 12.97);
insert into peca (quantidade, descricao, valor) values ('7', 'Gap Favorite Lip Balm', 72.03);
insert into peca (quantidade, descricao, valor) values ('9', 'OXYGEN', 70.93);
insert into peca (quantidade, descricao, valor) values ('9', 'Kionex', 62.13);
insert into peca (quantidade, descricao, valor) values ('4', 'Atenolol', 86.21);
insert into peca (quantidade, descricao, valor) values ('6', 'AIL-1', 11.9);
insert into peca (quantidade, descricao, valor) values ('2', 'Cilostazol', 15.04);
insert into peca (quantidade, descricao, valor) values ('3', 'TRETIN.X', 5.42);
insert into peca (quantidade, descricao, valor) values ('1', 'Childrens Acetaminophen', 29.84);
insert into peca (quantidade, descricao, valor) values ('7', 'CRESTOR', 57.16);
insert into peca (quantidade, descricao, valor) values ('3', 'Extra Strength Pain Reliever PM', 91.98);
insert into peca (quantidade, descricao, valor) values ('9', 'Carvedilol', 22.27);
insert into peca (quantidade, descricao, valor) values ('2', 'Galena Larix Special Order', 14.66);
insert into peca (quantidade, descricao, valor) values ('6', 'Mens Mitchum Advanced Invisible', 14.27);
insert into peca (quantidade, descricao, valor) values ('1', 'Amoxicillin and Clavulanate Potassium', 52.09);
insert into peca (quantidade, descricao, valor) values ('6', 'Ketoconazole', 3.03);
insert into peca (quantidade, descricao, valor) values ('0', 'Oxycodone and Acetaminophen', 28.39);
insert into peca (quantidade, descricao, valor) values ('7', 'REYATAZ', 90.06);
insert into peca (quantidade, descricao, valor) values ('0', 'Sucrets', 32.45);
insert into peca (quantidade, descricao, valor) values ('6', 'Governing Vessel Conception Vessel Meridian Opener', 21.61);
insert into peca (quantidade, descricao, valor) values ('4', 'piperacillin and tazobactam', 23.35);
insert into peca (quantidade, descricao, valor) values ('1', 'Nifedipine', 27.44);
insert into peca (quantidade, descricao, valor) values ('4', 'Pure Transformation Sheer Dark', 11.36);
insert into peca (quantidade, descricao, valor) values ('4', 'Mirtazapine', 59.78);
insert into peca (quantidade, descricao, valor) values ('7', 'Levetiracetam', 11.68);
